### ISSUE TITLE
Hi^^

### ISSUE THREAD

**Issue by beauhaus** [flopywood/hello-world#2]
I thought of you & your JS struggles...

http://www.asmarterwaytolearn.com/js/index-of-exercises.html

This is free, simple and actually really fun!

Hope yer still coding!

Take care,

Beau

**Comment by flopywood** [comment]
Thank you!!!!!! I'm doing a bit better now. 
I had to leave FCC for a while because I was getting all the answers to the challenges from the web and it felt like cheating. Besides, I wasn't learning anything that way so I went back to Codecademy and Khan Academy and I'm doing much better now. 
Still hard, but much better.
I'm also reading these books https://github.com/getify/You-Dont-Know-JS
How are you doing?

**Comment by flopywood** [comment]
Oh, I just got into CodeWars and I hope it takes me to the next level in terms of practice because Codecademy is rather easy next to what we see in FCC you should join too!

**Comment by flopywood** [comment]
Nevermind. Is much harder than FCC. Like, MUCH harder than FCC. I will have to keep learning and THEN go to CodeWars. :(

**Comment by beauhaus** [comment]
Right, I totally get that feeling of "cheating"... I click cmd+enter and then think I've absorbed it... :(

That link I sent doesn't let you get away with that, which is why it's so good.

I've heard of codewars, I'll def. check it out today--as well as the book.

I've decided to pull the trigger and go to a devbootcamp called DevMtn. I'm as psyched as I am terrified :) --but I'm using that energy to prepare.
👍 

IMO Here are some really great podcasts that are accessible and totally reinforce stuff that you've been learning (html, css, jquery, js stuff).

Shop-talk-show. (everything to do with css, html, js blah, blah)
http://shoptalkshow.com/

StartHere (practial advice and totally motivational for beginners)
(on itunes)

The Web Ahead. (calm, organized, step-wise conversations/interviews about general trends...it's often over my head, but it makes me feel smart)
http://5by5.tv/webahead

If I were you, if you like the "presentational" side of things (animation, etc...) I would DEFINITELY consider looking into SVG. It seems so opaque or inaccessble, at first, but after one or two hours, the feeling is like "Oh my god--wait! It's THAT easy? What was I so afraid of?" lol

Here's one (amateur :) ) effort:
http://codepen.io/LeoFib/pen/MeJLzX

SVG is great because it's like "programming" separate parts of an image. It is also not a skill that many people have...So being the only one around who is good at it makes you really desirable in the web world.

All the css stuff you've probably learnt TOTALLY applies, you haven't wasted your life learning that. :)

--Oh, also, I would start a twitter account as soon as you can. I don't do FB & I was so reluctant to do get on twitter (I've got better things to do with my life lol), but it's generally a good thing to do--if only to "establish yourself" on the net, follow great sources and see what they're working on etc.

I have a library of helpful stuff that I can send if you need a hand. It also helps me to keep in touch with someone else suffering through this... :) I talk to friends and family abt it and they just get this "glazed look" and wait for me to stop talking. :/

I'm at beau.html@gmail.com

Good Luck & happy coding!
